services:
  garage:
    image: dxflrs/garage:v1.0.0
    restart: unless-stopped
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data
    ports:
      - "3900:3900" # S3 API (upload/download)
      - "3903:3903" # Admin API + UI cơ bản
    environment:
      GARAGE_RPC_PUBLIC_ADDR: "auto" # tự detect IP
  garage-ui:
    image: khairul169/garage-webui:latest
    restart: unless-stopped
    ports:
      - "3909:3909"
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://localhost:3900" # hoặc IP máy nếu truy cập ngoài
      AUTH_USER_PASS: "admin:$$2y$$10$$Kg9f/Gc4wRQ7yIbzOx5V0./aNzocBHNu5cVGmP0kMTaYdFED6zOLy"
    depends_on:
      - garage
