metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "auto"          # tự detect IP

rpc_secret = "4425f5c26c5e11581d3223904324dcb5b5d5dfb14e5e7f35e38c595424f5f1e6" 

replication_factor = 1

[s3_api]
s3_region = "garage"
bind_addr = "0.0.0.0:3900"

[admin]
bind_addr = "0.0.0.0:3903"
admin_token = "dev1234567890abcdef"  # đổi random